import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Entrega - 4",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <header className="bg-black h-20 text-purple-500">
          <nav>
            <ul>
                <li><Link href="/">::.HOME</Link></li>
                <li><Link href="/produtos/camisa">::.Camisas</Link></li>
                <li><Link href="/produtos/tenis">::.Tenis</Link></li>
            </ul>
          </nav>
        </header>

        {children}
      </body>
    </html>
  );
}
